name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: "Run Jest unit tests"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: "checkout pr"

      - name: "install dependencies"
        run: npm install

      - name: "run tests"
        run: npm run test
