name: Issue commenter

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Dump context"
        run: echo '${( toJSON(github.event) )}' | jq
        shell: bash
