name: Test workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  mycooljob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hello
        run: echo "test"
        shell: bash
